name: Main

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on:
      - ubuntu-latest
      - windows-latest
      - macos-latest

    steps:

    - name: Run Laravel Migrate
      run: php artisan migrate --force

    - name: Laravel clear cache config
      run: php artisan config:clear --force
      
    - name: Laravel clear cache view
      run: php artisan view:clear --force

    - name: Laravel clear cache route
      run: php artisan route:clear --force
      
    - name: Laravel clear cache compile
      run: php artisan clear-compiled --force

    - name: Laravel clear cache client
      run: php artisan cache:clear --force

    - name: Laravel optimize
      run: php artisan optimize --force

    - name: Laravel clear cache session
      run: php artisan session:clear --force
