name: Main

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on:
      - ubuntu-latest

    steps:
    - name: Php Version
      run: php -v

    - name: Run Laravel Migrate
      run: php /home/u960392013/public_html/RedLanternApi/artisan migrate --force

    - name: Laravel clear cache config
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan config:clear --force
      
    - name: Laravel clear cache view
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan view:clear --force

    - name: Laravel clear cache route
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan route:clear --force
      
    - name: Laravel clear cache compile
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan clear-compiled --force

    - name: Laravel clear cache client
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan cache:clear --force

    - name: Laravel optimize
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan optimize --force

    - name: Laravel clear cache session
      run: /usr/bin/php /home/u960392013/public_html/RedLanternApi/artisan session:clear --force
